### ISSUE TITLE
Benchmark implementace

### ISSUE THREAD

**Issue by f3l1x** [uestla/YetORM#10]
Myslis, ze bys mohl ve volne chvili udelat implementaci do srovnani knihoven?

https://github.com/minetro/db-benchmark

**Comment by uestla** [comment]
[Done.](https://github.com/dg/db-benchmark/pull/9)

**Comment by f3l1x** [comment]
Ahoj.

Fungovalo ti to? Na Travis CI to spadne.

https://github.com/minetro/db-benchmark-logs/commit/38045a6e0f89a232ecc2b318a2dc09d902ca109d

**Comment by f3l1x** [comment]
Pridal jsem to do sve implementace.

https://github.com/minetro/db-benchmark-logs/commit/a4d8f44e73e66c11c8d79a7433b7ffa098a19e50
https://github.com/minetro/db-benchmark-logs/commit/4eed3587b335273541186cd0e6636d5d9e1f720f
https://github.com/minetro/db-benchmark-logs/commit/b46b5573c800494c919ce9492539d2e151cd15dc

Nevede si vubec spatne.

Diky :smile:
