### ISSUE TITLE
EntityCollection - toArray()

### ISSUE THREAD

**Issue by jmeinlschmidt** [uestla/YetORM#15]
using method toArray() on entity doesn't return the collection as an array of each entity. The PHP function iterator_to_array() which your method uses, converts only the highest object into an array. Is it the purpose?

I expect this method to work like this
```
foreach($entityCollection as $entity) {
  $response[] = $entity->toArray();
}
```

**Comment by uestla** [comment]
I don't get your point. Can you explain in more detail or perhaps show a more detailed example? What isn't working here?

**Comment by jmeinlschmidt** [comment]
Let's say I have an _EntityCollection_ including for ex. 5 rows (_Entities_). Now I need to send this collection via jSON, so I have to transform this collection into an array including every single **Entity** in it.

Using method _toArray()_ on _EntityCollection_ doesn't work (I think this is problem of PHP). PHP function _iterator_to_array()_ in your method transforms only the "highest-level" object into an array but everything else stays untouched and is an object of Entity or EntityCollection.

This block of code does the work

```
foreach($entityCollection as $entity) {
  $response[] = $entity->toArray();
}
```
It returns an array of arrays (single entities) like

```
[
  [
    "id" => 123,
    "name" => "Bob"
    ...
  ],
  [
    "id" => 124,
    "name" => "John"
    ...
  ],
]
```
This is what I would like to achieve.

**Comment by uestla** [comment]
I understand what you're trying to do but `iterator_to_array()` does not work like this.

One way to achieve this is to create a BaseEntity which implements `JsonSerializable` interface and use the power of entity reflection to get entity properties and their values.

[I actually created a gist with this example](https://gist.github.com/uestla/b7793c3b7a7906b8c9191edbeacdbf27) ;-)

Make sure to upgrade your YetORM version to 10.1.x.

**Comment by uestla** [comment]
ping @jmeinlschmidt

**Comment by uestla** [comment]
Inactive - closing.
