### ISSUE TITLE
'float' expected, 'double' given

### ISSUE THREAD

**Issue by jmeinlschmidt** [uestla/YetORM#16]
I've set @property float in my entity class. But when inserting number like 14.5. YetORM throws exception _Invalid type - 'float' expected, 'double' given_. Which is really big problem, because PHP doesn't see any difference between double and float. Using `floatval()` or (float) didn't help.

**Comment by uestla** [comment]
Oh I see. I personally didn't run into this issue yet.

Could you prepare a pull request with test included?

**Comment by jmeinlschmidt** [comment]
I really like this project. It's awesome, so I'm sorry for running this much issues. I will work this out.

**Comment by uestla** [comment]
Don't be sorry, it's OK :-)

I'll try to reproduce this error and fix it.

**Comment by uestla** [comment]
Thank you for the report.

The problem was that `gettype()` function returns "double" for floats so [this condition](https://github.com/uestla/YetORM/blob/0b9b372953d02f96f970a7638e73e4166de18097/src/YetORM/Reflection/AnnotationProperty.php#L100) did not match. It should be fixed now.
