### ISSUE TITLE
Persist return value

### ISSUE THREAD

**Issue by jmeinlschmidt** [uestla/YetORM#17]
After a successfull persisting only TRUE is returned. Wouldn't it be better to return ID or affected row instead?

**Comment by uestla** [comment]
The entity itself is "polluted" during persistence.

```php
$entity = new MyEntity;
$entity->getID(); // NULL
$repository->persist($entity);
$entity->getID(); // 123
```

I think boolean is OK here. I certainly wouldn't like to have some scalar ID(s) as a return value.

**Comment by jmeinlschmidt** [comment]
I'm sorry. Haven't noticed this option from your source code. My fault.

**Comment by uestla** [comment]
Please close this issue if everything's fine.
