### ISSUE TITLE
@inject v Modelu

### ISSUE THREAD

**Issue by jmeinlschmidt** [uestla/YetORM#18]
Snažím se využít model pro inteligentnější získávání informací. To bohužel zahrnuje potřebu načíst cizí třídu - repozitář. Ten se snažím načíst přes zápis `@inject`.

Jenže jak YetORM neprochází Nette, tak k načtení závislosti nedojde. Nějaké nápady jak jinak inteligentně nahrát závislost do modelu?

**Comment by uestla** [comment]
`@inject` se používá jen v presenterech, v modelu použij klasicky constructor.

**Comment by jmeinlschmidt** [comment]
```
class Book extends Entity {
	public $testRepository;

	public function __construct(TestRepository $testRepository) {
		$this->testRepository = $testRepository;
	}
}
```
Při takovémhle zápisu pak vzniká problém při předávání závislosti do constructoru. Musí se totiž při každé inicializaci předat závislost.

`$book = new Book($testRepository);`

Proto jsem se snažil využít zápis `@inject`. Tento zápis není úplně praktický, nemáš nápad na řešení?

**Comment by uestla** [comment]
Entita by ideálně neměla mít závislost na repozitáři jiné entity - čeho se snažíš docílit? Podobné závislosti by se měly řešit nejlépe o úroveň výše ve fasádě, apod.

**Comment by jmeinlschmidt** [comment]
Rozumím, že model by měl být co nejjednodušší. Každopádně se mi ve vyšších vrstvách hromadí defakto stejný blok kódu například na získání dalších informací k entitě, které se bohužel nedají vytáhnout tou jednoduchou referencí `$this->record->ref('table', 'entityId')`.

Tudíž mě napadlo tenhle blok kódu přesunout do Entity a data získávat přes repozitář.
