### ISSUE TITLE
Přetížení dynamického setteru/getteru

### ISSUE THREAD

**Issue by jakubboucek** [uestla/YetORM#19]
Mám Entitu, u níž potřebuju jeden setter přetížit. Ale nepřišel jsem na to, jak tu hodnotu potom uložit do entity.

```
setName($value)
{
   // nějaká validace
   $this->record->name;
}
```
Tohle ale nejde, protože si z nějakého důvodu [hlídá, aby se zapisovaly výhradně propetry z anotací](https://github.com/uestla/YetORM/blob/master/src/YetORM/Entity.php#L95).

Jako dokumentaci jsem použil fórum, ale tam se píše, že [medoty jsou odstraněny](https://forum.nette.org/cs/13583-yetorm-kvaziorm-nad-nette-database?p=3#p148641). 

Ale á vidím, že normálně fungují, je jen problém v tom, že [v kódu normálně jsou](https://github.com/uestla/YetORM/blob/master/src/YetORM/Reflection/EntityType.php#L80), jen jsou podivně zaslepeny. 

Je tedy možné mít vlastní gettery/settery pro některé property, nebo už to není podporováno?

**Comment by jakubboucek** [comment]
No ale i tak tam vidím problém:

I když nebudu mít současně setter a anotaci pro jednu property, tak nemůžu použít pro neanonotvané properties zápis `$entity->property = …` pro volání jejich setteru a musím extra volat přímo setter `$entity->setProperty(…)`. Tím je ovlivněno vnější rozhraní entity, kdy si musím hlídat jestli pracuju s propetry, která je anotovaná a nebo má vlastní setter. To je blbé, protože když propetry potřebuju přidat validaci, tak se změni API.

**Comment by uestla** [comment]
Souhlasím, není to vůbec šťastné.

Na druhou stranu jsem se chtěl vyhnout konfliktům anotací a metod a proto jsem z entity odstranil magické gettery, které jsou ve `SmartObject`u Nette (aby nebylo možné použít `$entity->test`, když mám jen definovanou metodu `test()`).
