### ISSUE TITLE
PHP7 + Nette 3

### ISSUE THREAD

**Issue by kravcik** [uestla/YetORM#22]
Ahoj Petře,

plánuješ vydat novou verzi pro Nette3 a PHP7.1? V Nette 3 bohužel bude chybět reflexe, můžu připravit pull-request, jestli máš zájem.

**Comment by uestla** [comment]
Ahoj, za PR budu rozhodně rád :-)

Díky!

**Comment by kravcik** [comment]
Jen jedna filosofická... 

Bude potřeba nahradit Reflection za nativní PHP... ten hází při chybějí property rovnou exception.

Tj. pro zachování nápovědy ("$entity->property") se ta bude muset udělat něco jako

```
try
{
   $entity->property
}
catch(PHPPRopertyException $e)
{
 throw new YetORMException;
}
```

Nějak mi v hlavě bliká majáček, že se mi to nelíbí, nějaký nápad? PR bych měl zvládnout do příštího týdne doufám.

**Comment by kravcik** [comment]
Draft je připravený k review. https://github.com/uestla/YetORM/pull/23
